<?php

/**
 * @file
 * Primary module hooks for Asignaturas Sincro module.
 */

/**
 * Implements hook_menu_local_tasks_alter().
 */
function asignaturas_sincro_menu_local_tasks_alter(&$data, $route_name, &$cacheability)
{
  $cacheability
    ->addCacheContexts([
      'user.permissions',
      'url',
    ]);
  $route_match = \Drupal::routeMatch();
  if (
    $route_match->getRouteName() == 'entity.node.latest_version' ||
    $route_match->getRouteName() == 'entity.node.edit_form'
  ) {
    $node = $route_match->getParameter('node');

    if ($node->bundle() == 'szvcata') {
      unset($data['tabs'][0]['asignaturas_sincro.confirmaEnviarAsignatura']);
    }
  }
}
